1. 定义RpcException

RpcException继承RuntimeException，定义特定错误码，专用于远程过程调用过程中产生的异常。

- X: 技术类异常
- Y: 业务类异常
- Z: 未知异常

![图片](https://mmbiz.qpic.cn/sz_mmbiz_png/rw1wCRwDbgaLrCWMXqja7DfhicRwyhbg9r7dYB7HfN27lRwSdphxwDJHoAyJRZKibuDdbJ001Of1oiaqztY450auw/640?wx_fmt=png&from=appmsg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

在使用时，使用rpc专用的异常错误码，方便定位排查。

![图片](https://mmbiz.qpic.cn/sz_mmbiz_png/rw1wCRwDbgaLrCWMXqja7DfhicRwyhbg9a0ibBlEZL2vibWXoVj1XAeL04WYKwV2CibC2nL7siaykOtHklCHTGTZcsg/640?wx_fmt=png&from=appmsg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

2. 超时异常重试

在发生网络超时的时候，可以进行重试，保证业务请求不因为网络原因而中断。

在代理类中，通过传入指定参数retry控制重试次数，使用while()循环进行重试，只对网络超时进行重试，其他异常直接抛出去。

![图片](https://mmbiz.qpic.cn/sz_mmbiz_png/rw1wCRwDbgaLrCWMXqja7DfhicRwyhbg9HfzavHlu4FGcqic4oEibMj2VPHVh9LyxCzNibgJQ1XIaIia2mMzZYWEwwQ/640?wx_fmt=png&from=appmsg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

3. 测试

在测试方法中通过睡眠模拟网络超时。特别的，只有8081请求端口访问时才超时，其他不会。

![图片](https://mmbiz.qpic.cn/sz_mmbiz_png/rw1wCRwDbgaLrCWMXqja7DfhicRwyhbg9XRl3xrAPLSXIkOU2RThiaP0bl9Ujbe7g79IBoj9SaALujJPfLbXV8Zw/640?wx_fmt=png&from=appmsg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

开始三个服务提供者，端口分别是8081,8082,8083

从服务消费者发起请求，睡眠时间是2秒，okhttp的连接超时时间设置为1秒，重试次数为1次。观察日志。

![图片](https://mmbiz.qpic.cn/sz_mmbiz_png/rw1wCRwDbgaLrCWMXqja7DfhicRwyhbg9bwmtnqib1iayTCiceaTsEMz0v1YeSPgZeSKhPc1oleTv3tkKnQjPNHNRg/640?wx_fmt=png&from=appmsg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![图片](https://mmbiz.qpic.cn/sz_mmbiz_png/rw1wCRwDbgaLrCWMXqja7DfhicRwyhbg98jMRgiaKq2yMia81EMQ0U4eO5zATA4rZJWL31SibFiaQL8bcRLCiaxYj6fQ/640?wx_fmt=png&from=appmsg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

当请求到8081 时，发生网络超时，自动进行了一次重试，第二次重试，在负载均衡时采用的是轮询，所以重试选择了8083，请求成功了。

![图片](https://mmbiz.qpic.cn/sz_mmbiz_png/rw1wCRwDbgaLrCWMXqja7DfhicRwyhbg97Q5kNaUspicuIRX6xvcH200iaJLdFcBvRtX03BWOicEn5kB5QfuObF40Q/640?wx_fmt=png&from=appmsg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

源码：

https://github.com/midnight2104/midnight-rpc/tree/lesson8